apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  argocd/app-name: ibbpy9q3f-java-springboot
  janus-idp.io/tekton: ibbpy9q3f-java-springboot
  backstage.io/kubernetes-id: ibbpy9q3f-java-springboot
  backstage.io/kubernetes-namespace: rhtap-app 
  app.kubernetes.io/part-of: ibbpy9q3f-java-springboot
resources:
  - deployment.yaml
  - route.yaml
  - service.yaml
